var message                       = {}

message.START = "<span>Hi, I’m TARA, your DIKSHA assistant. How may I help you today? <br> Select from one of the following options <ol> <li> To find and play content </li> <li> To download/update the DIKSHA mobile app </li><li> Other Queries</li></ol></span>"
message.CHOOSE_BOARD = "<span> Tell me which of the following board you belong to, so that I can assist you better Send the number corresponding to the board.: <ol> <li> 1. CBSE  </li><li> 2. State Board </li> </ol> </span>"
message.CBSE_MESSAGE = "<span> Please visit (<a href='https://diksha.gov.in/CBSE/explore'>diksha.gov.in/CBSE/explore</a>) to access eResources, videos, DFs and practice sheets from the topics in your syllabus. <br> Press 9 to go back to the previous menu or 0 to the main menu </span>"
message.CHOOSE_STATE_BOARD = "<span>Which of the following state boards you belong to? <ol><li> 1. Tamil Nadu </li><li> 2. Karnataka </li><li> 3. Gujarat </li><li> 4. Uttar Pradesh </li> </ol> </span>"
message.TN_BOARD = "<span>Please visit (<a href='https://diksha.gov.in/tn/explore'>diksha.gov.in/tn/explore</a>) to access eResources, videos, PDFs and practice sheets from the topics in your syllabus. Press 9 to go back to the previous menu or 0 to the main menu.</span>"
message.KA_BOARD = "<span>Please visit (<a href='https://diksha.gov.in/ka/explore'>diksha.gov.in/ka/explore</a>) to access eResources, videos, PDFs and practice sheets from the topics in your syllabus. Press 9 to go back to the previous menu or 0 to the main menu.</span>"
message.GJ_BOARD = "<span>Please visit (<a href='https://diksha.gov.in/gj/explore'>diksha.gov.in/gj/explore</a>) to access eResources, videos, PDFs and practice sheets from the topics in your syllabus. Press 9 to go back to the previous menu or 0 to the main menu.</span>"
message.UP_BOARD = "<span>Please visit (<a href='https://diksha.gov.in/up/explore'>diksha.gov.in/up/explore</a>) to access eResources, videos, PDFs and practice sheets from the topics in your syllabus. Press 9 to go back to the previous menu or 0 to the main menu.</span>"
message.PLAYSTORE = "<span>Please visit <a href='https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN​'>play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN​</a> </span>"
message.OTHER_OPTIONS = "<span> Please select from the following options- <ol> <li> How to scan using qr code?  </li> <li> Not able to Login </li><li> Others </li> </ol> </span>"
message.SCAN_QRCODE = "<span> Please visit: <a href='https://diksha.gov.in/help/getting-started/diksha-mobile-app/understanding-qr-code.html'>diksha.gov.in/help/getting-started/diksha-mobile-app/understanding-qr-code.html​</a>. Press 9 to go back to the previous menu or 0 to the main menu. </span>"
message.UNABLE_LOGIN = "<span>Please visit: <a href='https://diksha.gov.in/help/getting-started/sign-in/index.html'>diksha.gov.in/help/getting-started/sign-in/index.html​</a> . Press 9 to go back to the previous menu or 0 to the main menu </span>"
message.OTHERS = "<span>Please visit: <a href='https://diksha.gov.in/help/getting-started/explore-diksha/index.html'>diksha.gov.in/help/getting-started/explore-diksha/index.html​</a> . Press 9 to go back to the previous menu or 0 to the main menu. </span>"
message.UNKNOWN_OPTION = "Sorry, I do not understand what you’re asking. Please choose from the following options or press 0 for the main menu, so I can help you better"
message.SORRY = "Sorry, can you come again please?"

message.START_whatsapp = "Hi, I’m TARA, your DIKSHA assistant. How may I help you today? \n Select from one of the following options. Send the number corresponding to your choice \n 1. To find and play content \n 2. To download/update the DIKSHA mobile app \n 3. Other Queries"
message.CHOOSE_BOARD_whatsapp = "Tell me which of the following board you belong to, so that I can assist you better. Send the number corresponding to the board. \n1. CBSE  \n2. State Board "
message.CBSE_MESSAGE_whatsapp = "Please visit 'https://diksha.gov.in/CBSE/explore to access eResources, videos, DFs and practice sheets from the topics in your syllabus. Press 9 to go back to the previous menu or 0 to the main menu "
message.CHOOSE_STATE_BOARD_whatsapp = "Which of the following state boards you belong to? Send the number corresponding to your choice \n1. Tamil Nadu \n2. Karnataka \n3. Gujarat \n4. Uttar Pradesh"
message.TN_BOARD_whatsapp = "Please visit https://diksha.gov.in/tn/explore to access eResources, videos, PDFs and practice sheets from the topics in your syllabus. Press 9 to go back to the previous menu or 0 to the main menu."
message.KA_BOARD_whatsapp = "Please visit https://diksha.gov.in/ka/explore to access eResources, videos, PDFs and practice sheets from the topics in your syllabus. Press 9 to go back to the previous menu or 0 to the main menu."
message.GJ_BOARD_whatsapp = "Please visit https://diksha.gov.in/gj/explore to access eResources, videos, PDFs and practice sheets from the topics in your syllabus. Press 9 to go back to the previous menu or 0 to the main menu."
message.UP_BOARD_whatsapp = "Please visit https://diksha.gov.in/up/explore to access eResources, videos, PDFs and practice sheets from the topics in your syllabus. Press 9 to go back to the previous menu or 0 to the main menu."
message.PLAYSTORE_whatsapp = "Please visit https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN​"
message.OTHER_OPTIONS_whatsapp = "Please select from the following options. Send the number corresponding to your choice - \n1. How to scan using qr code?  \n2. Not able to Login \n3. Others"
message.SCAN_QRCODE_whatsapp = "Please visit: https://diksha.gov.in/help/getting-started/diksha-mobile-app/understanding-qr-code.html. Press 9 to go back to the previous menu or 0 to the main menu. "
message.UNABLE_LOGIN_whatsapp = "Please visit: https://diksha.gov.in/help/getting-started/sign-in/index.html. Press 9 to go back to the previous menu or 0 to the main menu "
message.OTHERS_whatsapp = "Please visit: https://diksha.gov.in/help/getting-started/explore-diksha/index.html. Press 9 to go back to the previous menu or 0 to the main menu. "
message.UNKNOWN_OPTION_whatsapp = "Sorry, I do not understand what you’re asking. Please choose from the following options or press 0 for the main menu, so I can help you better"
message.SORRY_whatsapp = "Sorry, can you come again please?"

message.START_telegram = "Hi, I’m TARA, your DIKSHA assistant. How may I help you today? \n Select from one of the following options. Send the number corresponding to your choice \n 1. To find and play content \n 2. To download/update the DIKSHA mobile app \n 3. Other Queries"
message.CHOOSE_BOARD_telegram = "Tell me which of the following board you belong to, so that I can assist you better. Send the number corresponding to the board.: \n1. CBSE  \n2. State Board "
message.CBSE_MESSAGE_telegram = "Please visit 'https://diksha.gov.in/CBSE/explore to access eResources, videos, DFs and practice sheets from the topics in your syllabus. Press 9 to go back to the previous menu or 0 to the main menu "
message.CHOOSE_STATE_BOARD_telegram = "Which of the following state boards you belong to? Send the number corresponding to your choice \n1. Tamil Nadu \n2. Karnataka \n3. Gujarat \n4. Uttar Pradesh"
message.TN_BOARD_telegram = "Please visit https://diksha.gov.in/tn/explore to access eResources, videos, PDFs and practice sheets from the topics in your syllabus. Press 9 to go back to the previous menu or 0 to the main menu."
message.KA_BOARD_telegram = "Please visit https://diksha.gov.in/ka/explore to access eResources, videos, PDFs and practice sheets from the topics in your syllabus. Press 9 to go back to the previous menu or 0 to the main menu."
message.GJ_BOARD_telegram = "Please visit https://diksha.gov.in/gj/explore to access eResources, videos, PDFs and practice sheets from the topics in your syllabus. Press 9 to go back to the previous menu or 0 to the main menu."
message.UP_BOARD_telegram = "Please visit https://diksha.gov.in/up/explore to access eResources, videos, PDFs and practice sheets from the topics in your syllabus. Press 9 to go back to the previous menu or 0 to the main menu."
message.PLAYSTORE_telegram = "Please visit https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN"
message.OTHER_OPTIONS_telegram = "Please select from the following options- \n1. How to scan using qr code?  \n2. Not able to Login \n3. Others"
message.SCAN_QRCODE_telegram = "Please visit: https://diksha.gov.in/help/getting-started/diksha-mobile-app/understanding-qr-code.html. Press 9 to go back to the previous menu or 0 to the main menu. "
message.UNABLE_LOGIN_telegram = "Please visit: https://diksha.gov.in/help/getting-started/sign-in/index.html. Press 9 to go back to the previous menu or 0 to the main menu "
message.OTHERS_telegram = "Please visit: https://diksha.gov.in/help/getting-started/explore-diksha/index.html. Press 9 to go back to the previous menu or 0 to the main menu. "
message.UNKNOWN_OPTION_telegram = "Sorry, I do not understand what you’re asking. Please choose from the following options or press 0 for the main menu, so I can help you better"

module.exports.message            = message;
